#!/bin/sh

cd css
./make-css-ui.sh
cd ..
lib/make-chas-uijs.sh
sed '/^.use strict.;$/d' lib/chas-uijs.js > lib/chas-uijs.js.tmp
mv lib/chas-uijs.js.tmp lib/chas-uijs.js
java -jar ext/compiler.jar --jscomp_off internetExplorerChecks --charset UTF-8 --js lib/chas-uijs.js --js_output_file lib/chas-uijs.min.js
