function pokaz(){'use_strict';
	var text=$('#ish').val();
	tex=text.trim();
	text=text.replace(/^\n/g,'');
	text=text.replace(/^\r/g,'');
	text=text.replace(/^\s/g,'');
	text=text.replace(/^\$/g,'');
	text=text.replace(/^\$/g,'');
	text=text.replace(/^\[/g,'');
	text=text.replace(/^\'/g,'');
	text=text.replace(/^\"/g,'');
	text=text.replace(/\$$/g,'');
	text=text.replace(/\$$/g,'');
	text=text.replace(/\]$/g,'');
	text=text.replace(/\'$/g,'');
	text=text.replace(/\"$/g,'');
	text=text.replace(/\n$/g,'');
	text=text.replace(/\r$/g,'');
	text=text.replace(/\s$/g,'');
	text=text.replace(/["'],/g,' ~~,');
	text=text.replace(/,["']/g,',~~ ');
	text=text.replace(/[\\][\\]/g,'\\');
	text='$$ '+text+' $$';
	$('#rez').html(text);
	MathJax.Hub.Typeset();
}
