'use strict';

var adresa={
	'//matematikalegko.ru/koordinatnaya-ploskost/uglovoj-koefficient-pryamoj-i-ne-tolko.html':
		[
			'..zdn/mat2014/B5/15.js',
		],
	'//matematikalegko.ru/dvigenie/zadachi-na-nahozhdenie-srednej-skorosti.html':
		[
			'..zdn/mat2014/B13/11.js',
		],
	'//matematikalegko.ru/stereometria-schar/zadachi-s-sharami.html':
		[
			'../zdn/mat2014/B13/11.js', 
			'../zdn/mat2014/B13/3.js', 
		], 

	'//matematikalegko.ru/okrugnost/ugol-vpisannyj-v-okruzhnost-zadachi.html':
		[
			'../zdn/mat2014/B8/13.js',
			'../zdn/mat2014/B8/11.js',
		],
	'//matematikalegko.ru/priyomy/radiany-v-gradusy-gradusy-v-radiany.html':
		[
			'../zdn/mlegko/M1/1.js',
		],
	'//matematikalegko.ru/koordinatnaya-ploskost/dlinna-otrezka-seredina-otrezka.html':
		[
			'../zdn/mat2014/B5/16.js',
		],
	'//matematikalegko.ru/praymougolni-treugolnik/zadachi-na-naxozhdenie-uglov.html':
		[
			'../zdn/mat2014/B5/17.js',
		],
	'//matematikalegko.ru/dvigenie/zadachi-na-dvizhenie-po-vode.html':
		[
			'../zdn/mat2014/B14/7.js',
			'../zdn/mat2014/B14/8.js',
		],
	'//matematikalegko.ru/issledovanie-funkcii-ege/najti-naibolshee-znachenie-funkcii-y-x3-3x-4.html':
		[
			'../zdn/mat2014/B15/20.js',
		],
	'//matematikalegko.ru/uravnenia/pokazatelnye-uravneniya-reschenija.html':
		[
			'../zdn/mat2014/B7/4.js',
			'../zdn/mat2014/B7/5.js',
		],
	'//matematikalegko.ru/formuli/proporciya-sostavlenie-proporcii.html':
		[
			'../zdn/mlegko/M1/1.js',
			'../zdn/mat2014/B5/17.js',
		],
	'//matematikalegko.ru/konus-cilindr/obyom-konusa-chast-3.html':
		[
			'../zdn/mat2014/B13/10-mlegko.js',
		],
	'//matematikalegko.ru/plocshadi-figur/krug-chasti-kruga-na-liste-v-kletku.html':
		[
			'../zdn/mat2014/B5/7.js',
		],
	'//matematikalegko.ru/formuli/zadachi-v11-obshhij-obzor-formuly.html':
		[
			'../zdn/mat2014/B5/8.js',
			'../zdn/mat2014/B5/9.js',
			'../zdn/mat2014/B10/2.js',
			'../zdn/mat2014/B10/3.js',
		],
	'//matematikalegko.ru/procenti/zadachi-na-procenty-chast-1.html':
		[
			'../zdn/mat2014/B2/4.js',
			'../zdn/mat2014/B2/6.js',
			'../zdn/mat2014/B2/11.js',
			'../zdn/mat2014/B2/12.js',
			'../zdn/mat2014/B2/13.js',
			'../zdn/mat2014/B2/29.js',
			'../zdn/mat2014/B2/31.js',
			'../zdn/mat2014/B2/32.js',
			'../zdn/mat2014/B2/33.js',
		],
	'//matematikalegko.ru/vektori/summa-vektorov-dlina-vektora-zadachi.html':
		[
			'../zdn/mat2014/B5/11.js',
			'../zdn/mat2014/B5/14.js',
		],
	'//matematikalegko.ru/mnogograniki/sostavnye-mnogogranniki-ploshhad-poverxnosti-i-obyom.html':
		[
			'../zdn/mat2014/B10/12.js',
		],
	'//matematikalegko.ru/konus-cilindr/obyom-konusa-chast-2.html':
		[
			'../zdn/mat2014/B13/1.js',
			'../zdn/mat2014/B13/9.js',
		],
	'//matematikalegko.ru/piramidi/pravilnye-piramidy-ploshhad-poverxnosti.html':
		[
			'../zdn/mat2014/B13/12.js',
		],
	'//matematikalegko.ru/dvigenie/po-dvum-parallelnym-zheleznodorozhnym-putyam-navstrechu-drug-drugu.html':
		[
			'../zdn/mat2014/B14/12.js',
		],
	'//matematikalegko.ru/prizmi/prizma-s-pravilnym-shestiugolnikom-v-osnovanii.html':
		[
			'../zdn/mat2014/B13/13.js',
		],
	'//matematikalegko.ru/priyomy/sinus-i-kosinus-zapomnit-navsegda.html':
		[
			'../zdn/tri/E5/1.js',
		],
/*	'':
		[
			'',
		],
	'':
		[
			'',
		],
*/

};

var hr=document.location.href.match(/[^#:]+/g);
if(hr && hr[1]){
	var shabl=adresa[hr[1]];
	if(shabl){
		chas.integrate("https://www.math.vsu.ru/chas-ege/sh/mini.html",{
			mini:{
				src:shabl,
			},
		},"100%",150,'chas-predupr');
		chas.autoIntegrated=1;
	}
}
