nabor.upak={E1:{1:function(){window.vopr.txt="$\\cos(a+b) =$<br/>";window.vopr.ver=["$ \\cos{a} \\cos{b} - \\sin{a} \\sin{b} $","$ \\cos{b} \\cos{a} - \\sin{b} \\sin{a} $","$ \\cos{a} \\cos{b} - \\sin{b} \\sin{a} $"];window.vopr.nev=["$ \\sin{a} \\cos{b} - \\cos{a} \\sin{b} $","$ \\sin{a} \\sin{b} + \\cos{a} \\cos{b} $","$ \\sin{a} \\sin{b} - \\cos{a} \\cos{b} $","$ \\cos{a} \\sin{b} - \\sin{a} \\cos{b} $"];AtoB()},2:function(){window.vopr.txt="$\\sin(a+b) =$<br/>";window.vopr.ver=["$ \\sin{a} \\cos{b} + \\cos{a} \\sin{b} $",
"$ \\cos{a} \\sin{b} + \\sin{a} \\cos{b} $"];window.vopr.nev=["$ \\sin{a} \\cos{b} - \\cos{a} \\sin{b} $","$ \\sin{a} \\sin{b} + \\cos{a} \\cos{b} $","$ \\sin{a} \\cos{b} - \\cos{a} \\sin{b} $","$ \\sin{a} \\sin{b} - \\cos{a} \\cos{b} $","$ \\sin{b} \\cos{a} + \\cos{a} \\sin{b} $"];AtoB()},3:function(){window.vopr.txt="$\\sin(a-b) =$<br/>";window.vopr.ver=["$ \\sin{a} \\cos{b} - \\cos{a} \\sin{b} $","$ \\cos{b} \\sin{a} - \\cos{a} \\sin{b} $","$ \\sin{a} \\cos{b} - \\sin{b} \\cos{a} $"];window.vopr.nev=
["$ \\sin{a} \\cos{b} + \\cos{a} \\sin{b} $","$ \\sin{a} \\sin{b} + \\cos{a} \\cos{b} $","$ \\sin{a} \\sin{b} - \\cos{a} \\cos{b} $","$ \\cos{a} \\cos{b} - \\sin{a} \\sin{b} $"];AtoB()},4:function(){window.vopr.txt="$\\cos(a-b) =$<br/>";window.vopr.ver=["$ \\cos{a} \\cos{b} + \\sin{a} \\sin{b} $","$ \\sin{b} \\sin{a} + \\cos{b} \\cos{a} $","$ \\cos{a} \\cos{b} + \\sin{b} \\sin{a} $","$ \\sin(a) \\sin(b) + \\cos(b) \\cos(a) $"];window.vopr.nev=["$ \\cos{a} \\cos{b} - \\sin{a} \\sin{b} $","$ \\sin{a} \\cos{b} - \\cos{a} \\sin{b} $",
"$ \\sin{a} \\sin{b} - \\cos{b} \\sin{a} $","$ \\cos{a} \\sin{b} + \\sin{a} \\cos{b} $"];AtoB()},5:function(){window.vopr.txt="$\\frac{\\mathrm{tg~}{a}-\\mathrm{tg~}{b}}{1+\\mathrm{tg~}{a} ~\\cdot~ \\mathrm{tg~}{b}} =$<br/>";window.vopr.ver=["$  \\mathrm{tg~}{(a-b)}$"];window.vopr.nev=["$ \\mathrm{tg ~}{(a+b)} $","$ \\mathrm{ctg~}{(a+b)}  $","$ \\mathrm{ctg~}{(a-b)}  $","$ \\mathrm{tg ~}{2a}  $"];AtoB()},main:function(){window.nomer=sluchch(1,5)}},E2:{1:function(){window.vopr.txt="$\\cos{2a} =$<br/>";
window.vopr.ver=["$ \\cos^{2}{a}-sin^{2}{a}  $","$ 2 \\cos^{2}{a} -1 $","$  1-2 \\sin^{2}{a} $"];window.vopr.nev=["$ \\cos{a}\\cdot\\cos{b} + \\sin{a}\\cdot\\sin{b}  $","$ \\sin^{2}{a} +\\cos^{2}{a}  $","$ 2 \\sin{a}\\cdot\\cos{a}  $","$ \\frac{1}{\\sin^{2}{a}}  $"];AtoB()},2:function(){window.vopr.txt="$2 \\sin{\\frac{a+b}{2}}\\cdot\\cos{\\frac{a-b}{2}} =$<br/>";window.vopr.ver=["$ \\sin{a}+\\sin{b}  $"];window.vopr.nev=["$ \\sin{2a}  $","$ \\cos{2a}  $","$ \\sin{a}-\\sin{b} $","$ \\cos{a}-\\cos{b} $",
"$ \\cos{a}+\\cos{b} $"];AtoB()},3:function(){window.vopr.txt="$2 \\sin{a}\\cdot\\cos{a} =$<br/>";window.vopr.ver=["$ \\sin{2a}  $"];window.vopr.nev=["$ \\cos{2a}  $","$ \\sin{(a+b)}  $","$ \\cos{(a+b)}  $","$ \\sin^{2}{a}  $"];AtoB()},main:function(){window.nomer=sluchch(1,3)}},E3:{10:function(){window.vopr.txt="$ \\cos{(\\frac{\\pi}{2}+a)}=$<br/>";window.vopr.ver=["$ -\\sin{a}  $"];window.vopr.nev=["$ \\cos{a}  $","$ -\\cos{a}  $","$ \\sin{a}  $"];AtoB()},11:function(){var a=[["-\\mathrm{ctg~}{a}",
"\\mathrm{ctg~}{(\\pi - a)}","\\mathrm{tg~}{(\\frac{\\pi}{2} +  a)}","\\mathrm{tg~}{(\\frac{3\\pi}{2} + a)}","\\mathrm{ctg~}{(2\\pi - a})"],["-\\mathrm{tg~}{a}","\\mathrm{tg~}{(\\pi - a)}","\\mathrm{ctg~}{(\\frac{\\pi}{2} +  a)}","\\mathrm{ctg~}{(\\frac{3\\pi}{2} + a)}","\\mathrm{tg~}{(2\\pi - a})"],["\\mathrm{tg~}{a}","\\mathrm{tg~}{(\\pi + a)}","\\mathrm{ctg~}{(\\frac{\\pi}{2} - a)}","\\mathrm{ctg~}{(\\frac{3\\pi}{2} - a)}"],["\\mathrm{ctg~}{a}","\\mathrm{ctg~}{(\\pi + a)}","\\mathrm{tg~}{(\\frac{\\pi}{2} -  a)}",
"\\mathrm{tg~}{(\\frac{3\\pi}{2} - a)}"]].shuffle(),b=a.splice(0,1)[0].iz(2);window.vopr.txt="$"+b[0]+"=$<br/>";window.vopr.ver=[b[1].ob$()];window.vopr.nev=a.matrToVect().ob$();AtoB()},1:function(){window.vopr.txt="$ \\sin{(\\frac{\\pi}{2}-a)}=$<br/>";window.vopr.ver=["$ \\cos{a}  $"];window.vopr.nev=["$ \\sin{a}  $","$ \\mathrm{tg~}{a}  $","$ -\\cos{a}  $","$ -\\sin{a}   $"];AtoB()},2:function(){window.vopr.txt="$ \\sin{(\\frac{\\pi}{2}+a)}=$<br/>";window.vopr.ver=["$ \\cos{a}  $"];window.vopr.nev=
["$ \\sin{a}  $","$ \\mathrm{tg~}{a}  $","$ -\\cos{a}  $","$ -\\sin{a}  $"];AtoB()},3:function(){window.vopr.txt="$ \\sin{(\\frac{3\\pi}{2}-a)}=$<br/>";window.vopr.ver=["$ -\\cos{a}  $"];window.vopr.nev=["$ \\sin{a}  $","$ \\cos{a}  $","$ -\\sin{a}  $"];AtoB()},4:function(){window.vopr.txt="$ \\sin{(\\frac{3\\pi}{2}+a)}=$<br/>";window.vopr.ver=["$ -\\cos{a}  $"];window.vopr.nev=["$ \\sin{a}  $","$ \\cos{a}  $","$ -\\sin{a}  $"];AtoB()},5:function(){window.vopr.txt="$ \\sin{(\\pi-a)}=$<br/>";window.vopr.ver=
["$ \\sin{a}  $"];window.vopr.nev=["$ \\cos{a}  $","$ -\\cos{a}  $","$ -\\sin{a}  $"];AtoB()},6:function(){window.vopr.txt="$ \\sin{(\\pi+a)}=$<br/>";window.vopr.ver=["$ -\\sin{a}  $"];window.vopr.nev=["$ \\cos{a}  $","$ -\\cos{a}  $","$ \\sin{a}  $"];AtoB()},7:function(){window.vopr.txt="$ \\sin{(2\\pi-a)}=$<br/>";window.vopr.ver=["$ -\\sin{a}  $"];window.vopr.nev=["$ \\cos{a}  $","$ -\\cos{a}  $","$ \\sin{a}  $"];AtoB()},8:function(){window.vopr.txt="$ \\sin{(2\\pi+a)}=$<br/>";window.vopr.ver=["$ \\sin{a}  $"];
window.vopr.nev=["$ \\cos{a}  $","$ -\\cos{a}  $","$ -\\sin{a}  $"];AtoB()},9:function(){window.vopr.txt="$ \\cos{(\\frac{\\pi}{2}-a)}=$<br/>";window.vopr.ver=["$ \\sin{a}  $"];window.vopr.nev=["$ \\cos{a}  $","$ -\\cos{a}  $","$ -\\sin{a}  $"];AtoB()},main:function(){window.nomer=sl(2)?sluchch(1,10):11}},E4:{1:function(){window.vopr.txt="$2 \\sin{\\frac{a+b}{2}}\\cdot\\cos{\\frac{a-b}{2}} =$<br/>";window.vopr.ver=["$ \\sin{a}+\\sin{b} $"];window.vopr.nev=["$ \\sin{2a} $","$ \\cos{2a} $","$ \\sin{a}-\\sin{b} $",
"$ \\cos{a}-\\cos{b} $","$ \\cos{a}+\\cos{b} $"];AtoB()},2:function(){window.vopr.txt="$2 \\sin{\\frac{a-b}{2}}\\cdot\\cos{\\frac{a+b}{2}} =$<br/>";window.vopr.ver=["$ \\sin{a}-\\sin{b}  $"];window.vopr.nev=["$ \\sin{2a} $","$ \\cos{2a} $","$ \\sin{a}+\\sin{b} $","$ \\cos{a}-\\cos{b} $","$ \\cos{a}+\\cos{b} $"];AtoB()},main:function(){window.nomer=sluchch(1,2)}}};
