nabor.upak={A1:{1:function(){var d=[2,8,10,16],c=d.iz();d.splice(d.indexOf(c),1);var d=d.iz(),a=sluchch(10,1E3),e=intoAnotherSystem(a,10,c),a=intoAnotherSystem(a,10,d);window.vopr.txt="Как представлено число "+e+"<sub>"+c+"</sub> в "+d+"-ной системе счисления?<br/>";window.vopr.ver=[a];for(var c=[],f=0;3>f;f++)a=sluchch(10,1E3),e=intoAnotherSystem(a,10,d),c[f]=e;window.vopr.nev=c;window.vopr.rsh="";AtoB()},2:function(){var d=sluchch(10,1E3),c=intoAnotherSystem(d,10,2),a=["единиц","значащих нулей"].iz(),
c="единиц"==a?(""+c).split("1").length-1:(""+c).split("0").length-1;window.vopr.txt="Сколько "+a+" в двоичной записи числа "+d+"?<br/>";window.vopr.ver=[c];d=[""];for(a=0;10>a;a++)d[a]=a;d.splice(d.indexOf(c),1);window.vopr.nev=d;window.vopr.rsh="";AtoB()},3:function(){var d=[8,10,16],c=d.iz();d.splice(d.indexOf(c),1);var a=d.iz(),d=sluchch(10,1E3),e=sluchch(d+2,d+10),f=sluchch(d+1,e-1),d=intoAnotherSystem(d,10,c),e=intoAnotherSystem(e,10,a),f=intoAnotherSystem(f,10,2);window.vopr.txt="Дано: a="+
d+"<sub>"+c+"</sub>, b="+e+"<sub>"+a+"</sub>. Какое из чисел С, записанных в двоичной системе счисления, удовлетворяет неравенству a &lt; C &lt; b?<br/>";window.vopr.ver=[f];c=[];for(a=0;2>a;a++)f=sluchch(10,d),f=intoAnotherSystem(f,10,2),c[a]=f;for(a=2;4>a;a++)f=sluchch(e,1E3),f=intoAnotherSystem(f,10,2),c[a]=f;window.vopr.nev=c;window.vopr.rsh="";AtoB()},4:function(){for(var d=[8,10,16],c=[],a=[],e=["единиц","значащих нулей"].iz(),f=[],b=0;4>b;b++){var g=sluchch(10,1E3),h=d.iz();a.push(h);h=intoAnotherSystem(g,
10,h);g=intoAnotherSystem(g,10,2);"единиц"==e?f.push((""+g).split("1").length-1):f.push((""+g).split("0").length-1);c.push(h)}b=f.iz();d=["ровно "+b,"наибольшее количество","наименьшее количество"].iz();g="0";g=d=="ровно "+b?c[f.indexOf(b)]:"наибольшее количество"==d?c[f.max()+1]:c[f.min()+1];window.vopr.txt="Даны 4 числа, они записаны с использованием различных систем счисления. Укажите среди этих чисел то, в двоичной записи которого содержится "+d+" "+e+". Если таких чисел несколько, укажите наибольшее из них.<br/>";
window.vopr.ver=[g+"<sub>"+a[c.indexOf(g)]+"</sub>"];a.splice(c.indexOf(g),1);c.splice(c.indexOf(g),1);e=[];for(b=0;3>b;b++)e[b]=c[b]+"<sub>"+a[b]+"</sub>";window.vopr.nev=e;window.vopr.rsh="";AtoB()},main:function(){window.nomer=sl(1,4)}},A2:{1:function(){(function(){Date.prototype.makeTime=function(){var a=this.getHours()+":";return a=10>this.getMinutes()?a+"0"+this.getMinutes():a+this.getMinutes()};for(var d=sluchch(4,5),c=["ТУЧЕВОЕ","ИВАНОВО","ОЛЕНЕВО","СЫРКОВО","ЛОМОВОЕ"].shuffle(),a=[],e="",
f=[],b=0;b<d;b++){a[b]=[];for(var g=0;g<d;g++)if(1<sluchch(1,4)&&b!=g&&(0!=b||1!=g)){a[b][g]=[];var h=sluchch(0,6E7),j=sluchch(h+36E5,65E6);a[b][g][0]=new Date(h);a[b][g][1]=new Date(j);e=e+"<tr><td>"+c[b]+"</td><td>"+c[g]+"</td><td>"+a[b][g][0].makeTime()+"</td><td>"+a[b][g][1].makeTime()+"</td></tr>";1==g&&f.push(a[b][g][1])}else a[b][g]=0}var e='<table border="1"><tr><td><b>Пункт отправления</td><td><b>Пункт прибытия</td><td><b>Время отправления</td><td><b>Время прибытия</td></tr>'+e+"<table>",
k=[],i=[];i[0]=new Date(sluchch(0,3E7));var m=new Date(2E9),l=0,n=function(){var b=i.length-1;k.push(l);for(var c=1;c<d;c++)0!=a[l][c]&&!k.hasElem(c)&&(i[b+1]=new Date(0),a[l][c][0].getHours()<i[b].getHours()||a[l][c][0].getHours()==i[b].getHours()&&a[l][c][0].getMinutes()==i[b].getMinutes()?i[b+1].setDate(i[b].getDate()+1):i[b+1].setDate(i[b].getDate()),i[b+1].setHours(a[l][c][1].getHours()),i[b+1].setMinutes(a[l][c][1].getMinutes()),1==c?i[b+1]<m&&(m=i[b+1]):(l=c,n(),k.length-=1,l=k[k.length-1],
i.length-=1))};n();window.vopr.txt="Путешественник пришел в "+i[0].makeTime()+" на автостанцию "+c[0]+"  и обнаружил следующее расписание местной сети автобусного сообщения. Определите самое раннее время, когда путешественник может оказаться в пункте "+c[1]+" согласно этому расписанию.<br/>"+e;window.vopr.ver=[m.makeTime()];c=[];for(b=0;b<f.length;b++)f[b].makeTime()!=m.makeTime()&&c.push(f[b].makeTime());for(b=f.length-1;4>b;b++)f=new Date(sluchch(0,6E7)),c[b]=f.makeTime();window.vopr.nev=c;window.vopr.rsh=
"";AtoB()})()},main:function(){window.nomer=sl(1,1)}},A3:{1:function(){for(var d=sluchch(2,4),c=[],a=0;4>a;a++)for(var e=!0;e;){var f=genLogFunc(d);(e=c.hasElem(f))||c.push(f)}for(var b=new Function("x","return "+parseLogic(c[0])),g=[],f=[],a=0;3>a;a++)g.push(slKrome(g,Math.pow(2,d)-1)),f[a]=make2Array(g[a],d);g=[];for(a=0;3>a;a++)g[a]=b(f[a]);for(b=1;4>b;b++)for(var e=!0,h=[];e;){e=new Function("x","return "+parseLogic(c[b]));for(a=0;3>a;a++)h[a]=e(f[a]);(e=g.equalAr(h))&&(c[b]=genLogFunc(d))}e=
"";for(b=0;b<d;b++)e+=("X"+(b+1)).vTag("b","").vTag("td","");e=(e+"F".vTag("b","").vTag("td","")).vTag("tr","");for(a=0;3>a;a++){e+="<tr>";for(b=0;b<d;b++)e+=(""+f[a][b]).vTag("td","");e+=(""+Number(g[a])).vTag("td","");e+="</tr>"}e=e.vTag("table",'border="1"');window.vopr.txt="Дан фрагмент таблицы истинности выражения F (см. таблицу). Какое выражение соответствует F?<br/>"+e+"<br/>";for(b=0;4>b;b++)c[b]=printLogic(c[b]);window.vopr.ver=c.splice(0,1);window.vopr.nev=c;window.vopr.rsh="";AtoB()},main:function(){window.nomer=
sl(1,1)}},A4:{1:function(){var d=genMask();window.vopr.txt="Для групповых операций с файлами используются маски имен файлов. Маска представляет собой последовательность букв, цифр и прочих допустимых в именах файлов символов, в которых также могут встречаться следующие символы: Символ «?» (вопросительный знак) означает ровно один произвольный символ. Символ «*» (звездочка) означает любую последовательность символов произвольной длины, в том числе «*» может задавать и пустую последовательность. Определите, какое из указанных имен файлов удовлетворяет маске:<br/>"+
d+"<br/>";window.vopr.nev=[];for(var c=0;3>c;c++)window.vopr.nev.push(genWrongWordForMask(d));window.vopr.ver=[genWordForMask(d)];window.vopr.rsh="";AtoB()},main:function(){window.nomer=sl(1,1)}},A5:{1:function(){var d=genAlg();window.vopr.txt=algInText(d)+"<br/>";window.vopr.nev=[];window.vopr.ver=[genWordForAlg(d)];for(var c=0;3>c;c++){var a="";do a=genWrongWordForAlg(d);while(window.vopr.nev.hasElem(a));window.vopr.nev.push(a)}window.vopr.rsh="";AtoB()},main:function(){window.nomer=sl(1,1)}},A6:{1:function(){function d(c,
a){c=c.replace(/\|\|/g," ИЛИ ");c=c.replace(/\&\&/g," И ");c=c.replace(/\!/g," НЕ ");return c=c.replace(/c\[(\d)\]/g,function(c,d){return a[Number(d)]})}(function(){for(var c=sluchch(5,8),a=sluchch(3,6),e="Иванов Петров Сидоров Малюков Силин Клеменс Холево Яшвили Бергер Численко".split(" ").iz(c),f=[],b=0;b<a;b++)f[b]=slLetter(f);for(b=0;b<a;b++)f[b]=f[b].toUpperCase();for(var g=[],h=0;h<c;h++){g[h]=[];for(b=0;b<a;b++)g[h][b]=sluchch(20)}for(var j="",j="Место".vTag("td")+"Участник".vTag("td"),b=0;b<
a;b++)j+=f[b].vTag("td");j=j.vTag("tr");for(h=0;h<c;h++){j+="<tr>";j+=(""+(h+1)).vTag("td")+e[h].vTag("td");for(b=0;b<a;b++)j+=(""+g[h][b]).vTag("td");j+="</tr>"}for(var j=j.vTag("table",'border="1"'),e=["<",">",">=","<="],k=sluchch(2,a-1),i=[],h=genLogFunc(k,"easy"),b=0;b<k;b++)i[b]=slKrome(i,a-1),h=h.replace("x["+b+"]","(c["+i[b]+"]"+e[sluchch(3)]+sluchch(20)+")");b=d(h,f);f=new Function("c","return "+h);for(h=a=0;h<c;h++)a+=f(g[h]);window.vopr.txt="Сколько записей в нижеследующем фрагменте турнирной таблицы удовлетворяют условию<br/><b>"+
b+"</b><br/>"+j+"<br/>";window.vopr.nev=[];for(b=0;3>b;b++)window.vopr.nev.push(slKrome(window.vopr.nev.concat(a),c));window.vopr.ver=[a];window.vopr.rsh="";AtoB()})()},main:function(){window.nomer=sl(1,1)}},B10:{1:function(){(function(){function d(a,c,d){this.name=a;this.file_size=c;this.download_time=d;this.get_download_speed=function(){return this.file_size/this.download_time}}for(var c="Вася Миша Никита Тарас Саша Петя".split(" ").iz(3),a=[],e=0;3>e;e++)a.push(new d(c[e],(2).pow(sl(4,6)),10*sl(1,
6)));for(var c=50*sl(5,15),f=-1,e=0;e<a.length;e++)f<a[e].get_download_speed()&&(f=a[e].get_download_speed());window.vopr.txt=a[0].name+" загружает на свой компьютер из Интернета файл размером "+a[0].file_size+" Мб за "+a[0].download_time+" секунд. "+a[1].name+" загружает файл размером "+a[1].file_size+" Мб за "+a[1].download_time+" секунд, а "+a[2].name+" загружает файл размером "+a[2].file_size+" Мб за "+a[2].download_time+" секунд.Сколько секунд будет загружаться файл размером "+c+" Мб на компьютер с наибольшей скоростью загрузки?";
window.vopr.ver=[c/f]})()},main:function(){window.nomer=sl(1,1);window.comment="Скорость передачи информации"}}};
