nabor.upak={A1:{1:function(){var d=[2,8,10,16],c=d.iz();d.splice(d.indexOf(c),1);var d=d.iz(),b=sluchch(10,1E3),e=intoAnotherSystem(b,10,c),b=intoAnotherSystem(b,10,d);window.vopr.txt="Как представлено число "+e+"<sub>"+c+"</sub> в "+d+"-ной системе счисления?<br/>";window.vopr.ver=[b];for(var c=[],f=0;3>f;f++)b=sluchch(10,1E3),e=intoAnotherSystem(b,10,d),c[f]=e;window.vopr.nev=c;window.vopr.rsh="";AtoB()},2:function(){var d=sluchch(10,1E3),c=intoAnotherSystem(d,10,2),b=["единиц","значащих нулей"].iz(),
c="единиц"==b?(""+c).split("1").length-1:(""+c).split("0").length-1;window.vopr.txt="Сколько "+b+" в двоичной записи числа "+d+"?<br/>";window.vopr.ver=[c];d=[""];for(b=0;10>b;b++)d[b]=b;d.splice(d.indexOf(c),1);window.vopr.nev=d;window.vopr.rsh="";AtoB()},3:function(){var d=[8,10,16],c=d.iz();d.splice(d.indexOf(c),1);var b=d.iz(),d=sluchch(10,1E3),e=sluchch(d+2,d+10),f=sluchch(d+1,e-1),d=intoAnotherSystem(d,10,c),e=intoAnotherSystem(e,10,b),f=intoAnotherSystem(f,10,2);window.vopr.txt="Дано: a="+
d+"<sub>"+c+"</sub>, b="+e+"<sub>"+b+"</sub>. Какое из чисел С, записанных в двоичной системе счисления, удовлетворяет неравенству a &lt; C &lt; b?<br/>";window.vopr.ver=[f];c=[];for(b=0;2>b;b++)f=sluchch(10,d),f=intoAnotherSystem(f,10,2),c[b]=f;for(b=2;4>b;b++)f=sluchch(e,1E3),f=intoAnotherSystem(f,10,2),c[b]=f;window.vopr.nev=c;window.vopr.rsh="";AtoB()},4:function(){for(var d=[8,10,16],c=[],b=[],e=["единиц","значащих нулей"].iz(),f=[],a=0;4>a;a++){var g=sluchch(10,1E3),h=d.iz();b.push(h);h=intoAnotherSystem(g,
10,h);g=intoAnotherSystem(g,10,2);"единиц"==e?f.push((""+g).split("1").length-1):f.push((""+g).split("0").length-1);c.push(h)}a=f.iz();d=["ровно "+a,"наибольшее количество","наименьшее количество"].iz();g="0";g=d=="ровно "+a?c[f.indexOf(a)]:"наибольшее количество"==d?c[f.max()+1]:c[f.min()+1];window.vopr.txt="Даны 4 числа, они записаны с использованием различных систем счисления. Укажите среди этих чисел то, в двоичной записи которого содержится "+d+" "+e+". Если таких чисел несколько, укажите наибольшее из них.<br/>";
window.vopr.ver=[g+"<sub>"+b[c.indexOf(g)]+"</sub>"];b.splice(c.indexOf(g),1);c.splice(c.indexOf(g),1);e=[];for(a=0;3>a;a++)e[a]=c[a]+"<sub>"+b[a]+"</sub>";window.vopr.nev=e;window.vopr.rsh="";AtoB()},main:function(){window.nomer=sl(1,4)}},A2:{1:function(){(function(){Date.prototype.makeTime=function(){var b=this.getHours()+":";return b=10>this.getMinutes()?b+"0"+this.getMinutes():b+this.getMinutes()};for(var d=sluchch(4,5),c=["ТУЧЕВОЕ","ИВАНОВО","ОЛЕНЕВО","СЫРКОВО","ЛОМОВОЕ"].shuffle(),b=[],e="",
f=[],a=0;a<d;a++){b[a]=[];for(var g=0;g<d;g++)if(1<sluchch(1,4)&&a!=g&&(0!=a||1!=g)){b[a][g]=[];var h=sluchch(0,6E7),j=sluchch(h+36E5,65E6);b[a][g][0]=new Date(h);b[a][g][1]=new Date(j);e=e+"<tr><td>"+c[a]+"</td><td>"+c[g]+"</td><td>"+b[a][g][0].makeTime()+"</td><td>"+b[a][g][1].makeTime()+"</td></tr>";1==g&&f.push(b[a][g][1])}else b[a][g]=0}var e='<table border="1"><tr><td><b>Пункт отправления</td><td><b>Пункт прибытия</td><td><b>Время отправления</td><td><b>Время прибытия</td></tr>'+e+"<table>",
k=[],i=[];i[0]=new Date(sluchch(0,3E7));var m=new Date(2E9),l=0,n=function(){var a=i.length-1;k.push(l);for(var c=1;c<d;c++)0!=b[l][c]&&!k.hasElem(c)&&(i[a+1]=new Date(0),b[l][c][0].getHours()<i[a].getHours()||b[l][c][0].getHours()==i[a].getHours()&&b[l][c][0].getMinutes()==i[a].getMinutes()?i[a+1].setDate(i[a].getDate()+1):i[a+1].setDate(i[a].getDate()),i[a+1].setHours(b[l][c][1].getHours()),i[a+1].setMinutes(b[l][c][1].getMinutes()),1==c?i[a+1]<m&&(m=i[a+1]):(l=c,n(),k.length-=1,l=k[k.length-1],
i.length-=1))};n();window.vopr.txt="Путешественник пришел в "+i[0].makeTime()+" на автостанцию "+c[0]+"  и обнаружил следующее расписание местной сети автобусного сообщения. Определите самое раннее время, когда путешественник может оказаться в пункте "+c[1]+" согласно этому расписанию.<br/>"+e;window.vopr.ver=[m.makeTime()];c=[];for(a=0;a<f.length;a++)f[a].makeTime()!=m.makeTime()&&c.push(f[a].makeTime());for(a=f.length-1;4>a;a++)f=new Date(sluchch(0,6E7)),c[a]=f.makeTime();window.vopr.nev=c;window.vopr.rsh=
"";AtoB()})()},main:function(){window.nomer=sl(1,1)}},A3:{1:function(){for(var d=sluchch(2,4),c=[],b=0;4>b;b++)for(var e=!0;e;){var f=genLogFunc(d);(e=c.hasElem(f))||c.push(f)}for(var a=new Function("x","return "+parseLogic(c[0])),g=[],f=[],b=0;3>b;b++)g.push(slKrome(g,Math.pow(2,d)-1)),f[b]=make2Array(g[b],d);g=[];for(b=0;3>b;b++)g[b]=a(f[b]);for(a=1;4>a;a++)for(var e=!0,h=[];e;){e=new Function("x","return "+parseLogic(c[a]));for(b=0;3>b;b++)h[b]=e(f[b]);(e=g.equalAr(h))&&(c[a]=genLogFunc(d))}e=
"";for(a=0;a<d;a++)e+=("X"+(a+1)).vTag("b","").vTag("td","");e=(e+"F".vTag("b","").vTag("td","")).vTag("tr","");for(b=0;3>b;b++){e+="<tr>";for(a=0;a<d;a++)e+=(""+f[b][a]).vTag("td","");e+=(""+Number(g[b])).vTag("td","");e+="</tr>"}e=e.vTag("table",'border="1"');window.vopr.txt="Дан фрагмент таблицы истинности выражения F (см. таблицу). Какое выражение соответствует F?<br/>"+e+"<br/>";for(a=0;4>a;a++)c[a]=printLogic(c[a]);window.vopr.ver=c.splice(0,1);window.vopr.nev=c;window.vopr.rsh="";AtoB()},main:function(){window.nomer=
sl(1,1)}},A4:{1:function(){var d=genMask();window.vopr.txt="Для групповых операций с файлами используются маски имен файлов. Маска представляет собой последовательность букв, цифр и прочих допустимых в именах файлов символов, в которых также могут встречаться следующие символы: Символ «?» (вопросительный знак) означает ровно один произвольный символ. Символ «*» (звездочка) означает любую последовательность символов произвольной длины, в том числе «*» может задавать и пустую последовательность. Определите, какое из указанных имен файлов удовлетворяет маске:<br/>"+
d+"<br/>";window.vopr.nev=[];for(var c=0;3>c;c++)window.vopr.nev.push(genWrongWordForMask(d));window.vopr.ver=[genWordForMask(d)];window.vopr.rsh="";AtoB()},main:function(){window.nomer=sl(1,1)}},A5:{1:function(){var d=genAlg();window.vopr.txt=algInText(d)+"<br/>";window.vopr.nev=[];window.vopr.ver=[genWordForAlg(d)];for(var c=0;3>c;c++){var b="";do b=genWrongWordForAlg(d);while(window.vopr.nev.hasElem(b));window.vopr.nev.push(b)}window.vopr.rsh="";AtoB()},main:function(){window.nomer=sl(1,1)}},A6:{1:function(){function d(c,
b){c=c.replace(/\|\|/g," ИЛИ ");c=c.replace(/\&\&/g," И ");c=c.replace(/\!/g," НЕ ");return c=c.replace(/c\[(\d)\]/g,function(c,d){return b[Number(d)]})}(function(){for(var c=sluchch(5,8),b=sluchch(3,6),e="Иванов Петров Сидоров Малюков Силин Клеменс Холево Яшвили Бергер Численко".split(" ").iz(c),f=[],a=0;a<b;a++)f[a]=slLetter(f);for(a=0;a<b;a++)f[a]=f[a].toUpperCase();for(var g=[],h=0;h<c;h++){g[h]=[];for(a=0;a<b;a++)g[h][a]=sluchch(20)}for(var j="",j="Место".vTag("td")+"Участник".vTag("td"),a=0;a<
b;a++)j+=f[a].vTag("td");j=j.vTag("tr");for(h=0;h<c;h++){j+="<tr>";j+=(""+(h+1)).vTag("td")+e[h].vTag("td");for(a=0;a<b;a++)j+=(""+g[h][a]).vTag("td");j+="</tr>"}for(var j=j.vTag("table",'border="1"'),e=["<",">",">=","<="],k=sluchch(2,b-1),i=[],h=genLogFunc(k,"easy"),a=0;a<k;a++)i[a]=slKrome(i,b-1),h=h.replace("x["+a+"]","(c["+i[a]+"]"+e[sluchch(3)]+sluchch(20)+")");a=d(h,f);f=new Function("c","return "+h);for(h=b=0;h<c;h++)b+=f(g[h]);window.vopr.txt="Сколько записей в нижеследующем фрагменте турнирной таблицы удовлетворяют условию<br/><b>"+
a+"</b><br/>"+j+"<br/>";window.vopr.nev=[];for(a=0;3>a;a++)window.vopr.nev.push(slKrome(window.vopr.nev.concat(b),c));window.vopr.ver=[b];window.vopr.rsh="";AtoB()})()},main:function(){window.nomer=sl(1,1)}}};
